highlighter: pygments
github: https://github.com/Rayi/
permalink: pretty
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: :compressed
kramdown:
  input: GFM
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Rayi"
      banner: "http://quanziio.qiniudn.com/b69b5cad275244e8d9a56236358a4739/banner"
      cover: "http://quanziio.qiniudn.com/5cd408020e7d67378fd876e08b3bd22b/cover"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      author: "Rayi"
      banner: "http://quanziio.qiniudn.com/b69b5cad275244e8d9a56236358a4739/banner"
      cover: "http://quanziio.qiniudn.com/5cd408020e7d67378fd876e08b3bd22b/cover"