highlighter: pygments
github: https://github.com/Rayi/
permalink: pretty
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: :compressed
kramdown:
  input: GFM
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "index"
      author: "Rayi"
      cover: "5cd408020e7d67378fd876e08b3bd22b"